---
galaxy_info:
  author: DevOps Team
  description: Role to set up Prometheus monitoring with Node Exporter and cAdvisor
  company: Your Company
  
  license: MIT
  
  min_ansible_version: "2.9"
  
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Amazon
      versions:
        - all
  
  galaxy_tags:
    - monitoring
    - prometheus
    - docker
    - node_exporter
    - cadvisor

dependencies: [] 