---
- name: Install CloudWatch agent on Sample servers
  hosts: all
  roles:
    - role: christiangda.amazon_cloudwatch_agent
      vars:
        cwa_conf_json_file_content: "{{ lookup('file', 'roles/amazon_cloudwatch_agent/files/cloudwatch_config.json') | from_json }}"
        cwa_agent_mode: "ec2"
        cwa_use_credentials: false
    
