---
- name: Execute ping using AWS SSM
  hosts: all
  gather_facts: no
  tasks:
    - name: Ping using SSM
      ansible.builtin.ping:
  vars:
    ansible_connection: aws_ssm
    ansible_aws_ssm_region: us-east-1
    ansible_python_interpreter: /usr/bin/python3
