---
# Playbook to deploy Prometheus monitoring with Node Exporter and cAdvisor
# Example usage:
#   ansible-playbook -i inventory.ini prometheus-monitoring-playbook.yml
#   ansible-playbook -i inventory.ini prometheus-monitoring-playbook.yml --tags "setup"
#   ansible-playbook -i inventory.ini prometheus-monitoring-playbook.yml --extra-vars "force_recreate=true"

- name: Deploy local development monitoring
  hosts: all
  become: yes
  vars:
    prometheus_remote_write_url: "https://prometheus-prod.provenance.ai/api/v1/write"
    force_recreate: false
  roles:
    - role: prometheus_monitoring
  tags:
    - monitoring
    - prometheus
    - development
    - prod
  serial: 10  # Run on 10 hosts in parallel


- name: Deploy local development monitoring
  hosts: localhost
  become: no
  vars:
    prometheus_remote_write_url: "https://prometheus-prod.example.com/api/v1/write"
    force_recreate: false
  roles:
    - role: prometheus_monitoring
  tags:
    - monitoring
    - prometheus
    - development
    - local 
  serial: 10  # Run on 10 hosts in parallel