plugin: aws_ec2
aws_profile: default 
regions:
  - us-east-1
  - ap-northeast-1 # Add Tokyo region


# Prevent duplicate hosts in inventory
allow_duplicated_hosts: false
filter:
  ＃tag:Role: "*" 
  instance-state-name: running

exclude_filters:
  - tag:Name:
    - 'workerenv*'

keyed_groups:
  - key: tags['Environment']
    prefix: env
  - key: tags['Project']
    prefix: project

compose:
  # Use the private IP address to connect to the host
  # (note: this does not modify inventory_hostname, which is set via I(hostnames))
  ansible_host: private_ip_address



