plugin: aws_ec2
aws_profile: default 
regions:
  - us-east-1

hostnames: 
  - instance-id



# Prevent duplicate hosts in inventory
allow_duplicated_hosts: false
filters:
  #tag:Role: "*" 
  instance-state-name: running

exclude_filters:
  - tag:karpenter.sh/nodepool:
    - 'default'
  - tag:AmazonECSManaged:
      - "*"
  - tag:eks:nodegroup-name: "*"

keyed_groups:
  - key: tags['Environment']
    prefix: env
  - key: tags['Project']
    prefix: project
  - key: private_ip_address
    prefix: ip

compose:
  # Use the private IP address to connect to the host
  # (note: this does not modify inventory_hostname, which is set via I(hostnames))
  ansible_host: private_ip_address



