---
all:
  hosts:
    192.168.33.10:
      ansible_connection: ssh
      ansible_user: element_devops
      ansible_ssh_private_key_file: ./credentials/id_rsa_element_devops
    app-release-server:
      ansible_connection: ssh
      ansible_host: din.discoverelement.com
      ansible_user: ceb
      ansible_ssh_private_key_file: ./credentials/id_rsa_ceb
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_connection: ssh
    ansible_user: element_devops
    ansible_ssh_private_key_file: ./credentials/id_rsa_element_devops
  children:
    ocr_db_master:
      hosts:
        192.168.33.10:
    ocr_db_slave:
      hosts:
        192.168.33.10:
    ocr_server:
      hosts:
        192.168.33.10:
        192.168.33.12:
        192.168.33.13:
    ocr_load_balancer:
      hosts:
        192.168.33.10:
    ocr_monitoring:
      hosts:
        192.168.33.10: