---
# Default variables for prometheus_monitoring role

# Docker Compose version
docker_compose_version: "v2.20.0"

# Service versions
node_exporter_version: "v1.8.1"
cadvisor_version: "v0.47.2"
prometheus_version: "v2.52.0"

# Installation directory
install_dir: "/home/ubuntu/prometheus-monitoring"

# Prometheus configuration
prometheus_config_dir: "{{ install_dir }}/config"
prometheus_data_dir: "{{ install_dir }}/data"

# Port configurations
node_exporter_port: 9100
cadvisor_port: 8080
prometheus_port: 9090

# Resource limits
node_exporter_memory_limit: "256M"
node_exporter_cpu_limit: "0.5"
cadvisor_memory_limit: "512M"
cadvisor_cpu_limit: "0.5"
prometheus_memory_limit: "1G"
prometheus_cpu_limit: "1.0"

# Remote write configuration
prometheus_remote_write_url: "https://prometheus-prod.mock.com/api/v1/write"

# Health check configuration
health_check_interval: "30s"
health_check_timeout: "10s"
health_check_retries: 3 