---
# Handlers for prometheus_monitoring role

- name: Restart Prometheus monitoring stack
  shell: |
    docker compose -p prometheus down -v
    sleep 5
    docker compose -p prometheus up -d
  args:
    chdir: "{{ install_dir }}"
  become: no